development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:0b0063d95a06d1a23a05c8502ec03d02@crestfish.redistogo.com:11548/
  channel_prefix: holistick_production
