meta_product_name: "The Holistic Panda"
meta_title: "The Holistic Panda - Holistic Wellness for the Busy Soul"
meta_description: "Find & book a diverse range of holistic wellness services to achieve your health goals. Sign up and start your wellness journey with The Holistic Panda today!"
meta_image: "meta.png" # should exist in `app/assets/images/`
twitter_account: ""   # required for Twitter Cards
