:concurrency: 2
:verbose: true
:timeout: 8
:queues:
  # Queue priority:
  # https://github.com/mperham/sidekiq/wiki/Advanced-Options
  # https://mikerogers.io/2019/06/06/rails-6-sidekiq-queues
  - mailers
  - default
  - active_storage_analysis
  - active_storage_purge
